### ISSUE TITLE
TX and RX are swapped

### ISSUE THREAD

**Issue by alyf80** [danielkucera/tuya-esp-adapter#2]
FYI,

Current master (031c61bf6d1d21104408cedd763a9be0f04462ce) has the TX and RX pins swapped; the pinout was actually correct _before_ the "fix" in that commit.
The issue is in the ESP module pinout: the pin towards the antenna should be TX, not RX.

This means the adapter will not work in any device that communicates with the ESP8266 via serial port -- e.g. anything containing a BL0940/BL0942 energy monitoring chip.

**Comment by danielkucera** [comment]
Hi, I think I don't understand. I wanted it to be 1:1 compatible with TYWE2S and it has those pins vice-versa. Am I not right?

**Comment by alyf80** [comment]
Looking at the KiCAD PCB file in 031c61bf6d1d21104408cedd763a9be0f04462ce, this is correct:
![image](https://user-images.githubusercontent.com/14372014/147956779-6d016c74-9722-482b-915e-7a29b4170963.png)

This, however, is not:
![image](https://user-images.githubusercontent.com/14372014/147956853-1acfa86f-97be-42d1-b534-a499c70a19dc.png)
Pin 16 of the ESP module is TX (not RX) and pin 15 is RX (not TX).

I am using the adapter with an ESP-12F in one of [these](https://it.aliexpress.com/item/4000478798085.html), which have a serial-connected BL0942 chip and come with a [CB2S](https://developer.tuya.com/en/docs/iot/cb2s-module-datasheet?id=Kafgfsa2aaypq) module (BK7231N-based, pinout is the same as TYWE2S); energy monitoring will only work after cutting the TX/RX connections and reattaching them the other way round.

**Comment by danielkucera** [comment]
But what configuration are you using for tasmota?

**Comment by alyf80** [comment]
`Template{"NAME":"Elivco Power Monitoring Plug","GPIO":[0,3200,7616,7520,0,32,0,0,0,576,224,0,0,0],"FLAG":0,"BASE":18}`

![image](https://user-images.githubusercontent.com/14372014/147959507-311e1900-9bf8-4355-947c-e43c5ccc6697.png)

**Comment by danielkucera** [comment]
I wanted it to be compatible with this config: https://templates.blakadder.com/athom_PG01EU16A.html
In your case, you should be able to make it work with just swapping PIN1 and PIN3 config

**Comment by alyf80** [comment]
In that device the ESP is interfaced to the EM chip via the SEL/CF pins -- basically the BL0937 generates a pair of pulse trains whose timing is a function of the actual voltage/current; the ESP samples them via GPIO pins and then computes energy information in software. There is no serial communication involved, so that device/configuration is not affected by this issue.

In my device, energy monitoring is done completely in the EM chip. The ESP is only connected to the BL0942 via its UART interface; every second the ESP sends a "poll" command to the BL0942 and gets back a 22-byte packet containing fully-decoded 24-bit values for voltage, current, energy and lots of other stuff. This requires a working serial connection, so it will not function if the ESP serial pins are wired incorrectly.

I can't just swap pins in the configuration -- UART TX and RX are hardware functions, and unlike GPIOs they cannot be freely reassigned on the ESP8266.

(And yes, the tasmota UI will allow you to assign "serial TX" and "serial RX" to any pin, but that's a bug in tasmota and will not result in a working configuration...)

**Comment by danielkucera** [comment]
I am starting to understand. But isn't tasmota using SoftwareSerial when the pins don't match HW serial pins? So it could potentially work if you set them as I proposed. Have you tried it?

**Comment by alyf80** [comment]
I had tried that, and it did not work. You are right, however: the way the BL09XX driver is written, tasmota should use a software serial implementation if neither the TX nor the RX pin matches a HW serial pin (I didn't know that!). I suspect that's because the BL0942 requires a pullup on its UART TX line, while tasmota's software serial implementation sets up the RX GPIO pin without a pullup. I'll have to look into that.

Leaving all configuration issues and workarounds aside, however, my original issue is with the hardware: right now an "adapted" ESP is not a drop-in replacement for a Tuya module, because the RX and TX pins of the ESP are swapped wrt the Tuya pinout.

**Comment by danielkucera** [comment]
Good, now I am confident to revert the changes as it makes sense to me. Sorry for the inconvenience with the wrong pinout.

**Comment by alyf80** [comment]
No problem and thanks for the project!

**Comment by danielkucera** [comment]
You are welcome.
